name: Grab data and deploy Datasette

on:
  push:
    branches:
    - master
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: actions/cache@v1
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Grab data
      run: |
        rm -f nhs_ods.db
        nhs_admin collect    
    - name: Commit and push
      run: |-
        git config --global user.email "nhs-admindata-bot@example.com"
        git config --global user.name "NHS-admindata-bot"
        git diff --quiet || (git add nhs_ods.db && git commit -m "Updated NHS ODS db")
        git push
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Deploy Datasette using Zeit Now
      env:
        NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
      run: |-
        datasette publish now nhs_ods.db \
          --token $NOW_TOKEN \
          --project nhs-ods \
          --public
